# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftmenu = QtWidgets.QFrame(self.centralwidget)
        self.leftmenu.setGeometry(QtCore.QRect(9, -1, 151, 561))
        self.leftmenu.setStyleSheet("\n"
"background-color:#374550;\n"
"")
        self.leftmenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftmenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftmenu.setObjectName("leftmenu")
        self.label = QtWidgets.QLabel(self.leftmenu)
        self.label.setGeometry(QtCore.QRect(30, 40, 101, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.leftmenu)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #f6f3ee;\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.leftmenu)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 111, 31))
        self.pushButton.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.leftmenu)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 200, 111, 31))
        self.pushButton_2.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("inventoryb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.leftmenu)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 250, 111, 31))
        self.pushButton_3.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ordersb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.leftmenu)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 300, 111, 31))
        self.pushButton_4.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("salesb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.leftmenu)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 490, 111, 31))
        self.pushButton_5.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logoutb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 0, 681, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.dashboardw = QtWidgets.QWidget(self.page)
        self.dashboardw.setGeometry(QtCore.QRect(0, 0, 681, 561))
        self.dashboardw.setStyleSheet("background-color:#ffffff;")
        self.dashboardw.setObjectName("dashboardw")
        self.dateTimeLabel = QtWidgets.QLabel(self.dashboardw)
        self.dateTimeLabel.setGeometry(QtCore.QRect(0, 0, 681, 101))
        self.dateTimeLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: #f0f0f0;\n"
"    border: 2px solid #8d2721;\n"
"    padding: 10px;\n"
"    text-align: center;\n"
"}\n"
"")
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.salesbox = QtWidgets.QFrame(self.dashboardw)
        self.salesbox.setGeometry(QtCore.QRect(40, 120, 181, 101))
        self.salesbox.setStyleSheet("#salesbox\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.salesbox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.salesbox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.salesbox.setObjectName("salesbox")
        self.label_8 = QtWidgets.QLabel(self.salesbox)
        self.label_8.setGeometry(QtCore.QRect(40, 70, 91, 21))
        self.label_8.setStyleSheet("color:#004aad;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.salesbox)
        self.label_9.setGeometry(QtCore.QRect(40, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#c9cc7f")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.salesbox)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 31, 20))
        self.label_10.setStyleSheet("background-color: transparent;\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("salel.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.salesbox)
        self.label_11.setGeometry(QtCore.QRect(110, 20, 31, 21))
        self.label_11.setStyleSheet("background-color: transparent;\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("up.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.ordersbox = QtWidgets.QFrame(self.dashboardw)
        self.ordersbox.setGeometry(QtCore.QRect(260, 120, 181, 101))
        self.ordersbox.setStyleSheet("#ordersbox\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.ordersbox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ordersbox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ordersbox.setObjectName("ordersbox")
        self.label_16 = QtWidgets.QLabel(self.ordersbox)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.label_16.setStyleSheet("background-color: transparent;\n"
"")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("salel.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.ordersbox)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:#c9cc7f")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.ordersbox)
        self.label_18.setGeometry(QtCore.QRect(90, 30, 31, 21))
        self.label_18.setStyleSheet("background-color: transparent;\n"
"")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("up.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.ordersbox)
        self.label_19.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_19.setStyleSheet("color:#004aad;")
        self.label_19.setObjectName("label_19")
        self.revenue = QtWidgets.QFrame(self.dashboardw)
        self.revenue.setGeometry(QtCore.QRect(480, 120, 171, 101))
        self.revenue.setStyleSheet("#revenue\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.revenue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.revenue.setFrameShadow(QtWidgets.QFrame.Raised)
        self.revenue.setObjectName("revenue")
        self.label_20 = QtWidgets.QLabel(self.revenue)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.label_20.setStyleSheet("background-color: transparent;\n"
"")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("salel.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.revenue)
        self.label_21.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:#c9cc7f")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.revenue)
        self.label_22.setGeometry(QtCore.QRect(110, 30, 31, 21))
        self.label_22.setStyleSheet("background-color: transparent;\n"
"")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("up.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.revenue)
        self.label_23.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_23.setStyleSheet("color:#004aad;")
        self.label_23.setObjectName("label_23")
        self.chartd = QtWidgets.QFrame(self.dashboardw)
        self.chartd.setGeometry(QtCore.QRect(40, 240, 281, 301))
        self.chartd.setStyleSheet("#chartd\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.chartd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chartd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chartd.setObjectName("chartd")
        self.btnViewSalesReport = QtWidgets.QPushButton(self.chartd)
        self.btnViewSalesReport.setGeometry(QtCore.QRect(70, 260, 101, 23))
        self.btnViewSalesReport.setStyleSheet("QPushButton{color: blue;\n"
"text-decoration: underline;\n"
"border: none;\n"
"background: transparent;}\n"
"QPushButton:hover {\n"
"color:#8d2721;\n"
"}\n"
"")
        self.btnViewSalesReport.setObjectName("btnViewSalesReport")
        self.frameBestSellersChart = QtWidgets.QFrame(self.chartd)
        self.frameBestSellersChart.setGeometry(QtCore.QRect(20, 20, 241, 241))
        self.frameBestSellersChart.setStyleSheet("background-color: white;\n"
"border: none;\n"
"")
        self.frameBestSellersChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBestSellersChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBestSellersChart.setObjectName("frameBestSellersChart")
        self.label_3 = QtWidgets.QLabel(self.dashboardw)
        self.label_3.setGeometry(QtCore.QRect(340, 360, 47, 13))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.inventoryw = QtWidgets.QWidget(self.page_4)
        self.inventoryw.setGeometry(QtCore.QRect(0, 0, 681, 551))
        self.inventoryw.setObjectName("inventoryw")
        self.label_4 = QtWidgets.QLabel(self.inventoryw)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 271, 101))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.ordersw = QtWidgets.QWidget(self.page_2)
        self.ordersw.setGeometry(QtCore.QRect(0, 0, 681, 551))
        self.ordersw.setObjectName("ordersw")
        self.label_5 = QtWidgets.QLabel(self.ordersw)
        self.label_5.setGeometry(QtCore.QRect(50, 70, 301, 131))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.salesw = QtWidgets.QWidget(self.page_3)
        self.salesw.setGeometry(QtCore.QRect(0, 0, 681, 551))
        self.salesw.setObjectName("salesw")
        self.label_6 = QtWidgets.QLabel(self.salesw)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 231, 121))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "J & J ELEVATE"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Inventory"))
        self.pushButton_3.setText(_translate("MainWindow", "Orders"))
        self.pushButton_4.setText(_translate("MainWindow", "Sales"))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.dateTimeLabel.setText(_translate("MainWindow", "March 31, 2025 Monday 09 : 10 : 54 AM"))
        self.label_8.setText(_translate("MainWindow", "Today’s Sales"))
        self.label_9.setText(_translate("MainWindow", "80,000"))
        self.label_17.setText(_translate("MainWindow", "300"))
        self.label_19.setText(_translate("MainWindow", "Today’s total orders"))
        self.label_21.setText(_translate("MainWindow", "40, 000"))
        self.label_23.setText(_translate("MainWindow", "Today’s revenue"))
        self.btnViewSalesReport.setText(_translate("MainWindow", "View Sales Report"))
        self.label_3.setText(_translate("MainWindow", "kapoy na"))
        self.label_4.setText(_translate("MainWindow", "INVENTORRRRRRY"))
        self.label_5.setText(_translate("MainWindow", "TextLabelORDERSSSSSSSS"))
        self.label_6.setText(_translate("MainWindow", "TextLabelSALESSSSSSS"))
